CREATE TABLE "blog_post" (
	"id" text PRIMARY KEY NOT NULL,
	"title_ar" text NOT NULL,
	"title_en" text NOT NULL,
	"slug_ar" text NOT NULL,
	"slug_en" text NOT NULL,
	"excerpt_ar" text NOT NULL,
	"excerpt_en" text NOT NULL,
	"content_ar" text NOT NULL,
	"content_en" text NOT NULL,
	"featured_image_url" text NOT NULL,
	"image_urls" json DEFAULT '[]'::json NOT NULL,
	"keywords_ar" json DEFAULT '[]'::json NOT NULL,
	"keywords_en" json DEFAULT '[]'::json NOT NULL,
	"tags_ar" json DEFAULT '[]'::json NOT NULL,
	"tags_en" json DEFAULT '[]'::json NOT NULL,
	"meta_description_ar" text NOT NULL,
	"meta_description_en" text NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"published_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "blog_post_slug_ar_unique" UNIQUE("slug_ar"),
	CONSTRAINT "blog_post_slug_en_unique" UNIQUE("slug_en")
);
